//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the MSBuild WriteCodeFragment class.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Tasks.Tests")]
[assembly: InternalsVisibleTo("Helper.WebServer")]
[assembly: InternalsVisibleTo("com.unity.editor.tasks.tests")]
