//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CA2243

[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.59.39583")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.59+9f9ac7747e")]
#if NETSTANDARD || NETFRAMEWORK || NETCOREAPP
[System.CodeDom.Compiler.GeneratedCode("Nerdbank.GitVersioning.Tasks","3.4.255.64262")]
#endif
#if NETFRAMEWORK || NETCOREAPP || NETSTANDARD2_0 || NETSTANDARD2_1
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
internal static partial class ThisAssembly {
    internal const string AssemblyConfiguration = "Release";
    internal const string AssemblyFileVersion = "1.0.59.39583";
    internal const string AssemblyInformationalVersion = "1.0.59+9f9ac7747e";
    internal const string AssemblyName = "SpoiledCat.Git";
    internal const string AssemblyTitle = "SpoiledCat.Git";
    internal const string AssemblyVersion = "1.0.0.0";
    internal static readonly System.DateTime GitCommitDate = new System.DateTime(638995060490000000L, System.DateTimeKind.Utc);
    internal const string GitCommitId = "9f9ac7747ec0e418fa6aa9f37ae1864c42768d83";
    internal const bool IsPrerelease = false;
    internal const bool IsPublicRelease = true;
    internal const string RootNamespace = "Git";
}
