//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CA2243

[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.60.41209")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.60+f9a0bb1c1c")]
#if NETSTANDARD || NETFRAMEWORK || NETCOREAPP
[System.CodeDom.Compiler.GeneratedCode("Nerdbank.GitVersioning.Tasks","3.4.255.64262")]
#endif
#if NETFRAMEWORK || NETCOREAPP || NETSTANDARD2_0 || NETSTANDARD2_1
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
internal static partial class ThisAssembly {
    internal const string AssemblyConfiguration = "Release";
    internal const string AssemblyFileVersion = "1.0.60.41209";
    internal const string AssemblyInformationalVersion = "1.0.60+f9a0bb1c1c";
    internal const string AssemblyName = "SpoiledCat.Git.UI";
    internal const string AssemblyTitle = "SpoiledCat.Git.UI";
    internal const string AssemblyVersion = "1.0.0.0";
    internal static readonly System.DateTime GitCommitDate = new System.DateTime(638995064870000000L, System.DateTimeKind.Utc);
    internal const string GitCommitId = "f9a0bb1c1c664240693fed7c4198ccd3667aea92";
    internal const bool IsPrerelease = false;
    internal const bool IsPublicRelease = true;
    internal const string RootNamespace = "UI";
}
