//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersionAttribute("2.1.0.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2.1.0.43997")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2.1.0+ddab5424a7")]
#if NETSTANDARD || NETFRAMEWORK || NETCOREAPP
[System.CodeDom.Compiler.GeneratedCode("Nerdbank.GitVersioning.Tasks","3.1.38.8029")]
#endif
internal static partial class ThisAssembly {
    internal const string AssemblyVersion = "2.1.0.0";
    internal const string AssemblyFileVersion = "2.1.0.43997";
    internal const string AssemblyInformationalVersion = "2.1.0+ddab5424a7";
    internal const string AssemblyName = "Unity.Editor.Tasks";
    internal const string AssemblyTitle = "Unity.Editor.Tasks";
    internal const string AssemblyConfiguration = "Release";
    internal const string GitCommitId = "ddab5424a7d6ecae6e65ac8700f468e226a2fbb7";
    internal static readonly System.DateTime GitCommitDate = new System.DateTime(637208447970000000L, System.DateTimeKind.Utc);
    internal const string RootNamespace = "Unity.Editor.Tasks";
}
