{% metadata_file .yamato_config/config.yml %}
---
build:
  name: Build
  agent:
    type: {{ build_agent_type }}
    image: {{ build_agent_image }}
    flavor: {{ build_agent_flavor }}
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

  commands:
    - powershell scripts\Get-Deps.ps1
    - build.cmd
    - test.cmd
    - pack.cmd

  artifacts:
    packman:
      paths:
        - "upm-ci~/**/*"
    binaries:
      paths:
        - "build/bin/**/*"
    tests:
      paths:
        - "build/tests/bin/**/*"
        - "tests/**/TestResults/*"
    sources:
      paths:
        - "build/packages/**/*"
